### ISSUE TITLE
멀티 커넥트

### ISSUE THREAD

**Issue by taisi5446** [nano-roboscan/NSL-1110AV-ROS1#1]
readme등 을 통해 단일 기기에 대한 연결에 성공하였습니다.

다만 복수의 라이다 연결방법에 대한 설명이  없어 문의드립니다.

복수의 라이다를 연결하는 방법이 있을까요?

**Comment by nano-roboscan** [comment]
1. USB 멀티커넥트 사용불가
 USB의 연결은 ip가 192.168.7.2로 고정되어 있기 때문에 USB로는 멀티커넥트가 어렵습니다.

2. Ehternet 멀티커넥트 사용가능 
 Ethernet으로 사용하게 되면 현재 기본 IP가 192.168.2.100일텐데 라이다의 IP를 변경해주는 batch 파일을 사용하여 2개 이상의 라이다를 사용할 수 있습니다.
 라이다에 전원을 인가하고 usb를 연결한 뒤에 라이다 전면의 LED가 깜빡이면서 준비상태일 때 첨부된 batch파일을 실행하여 업데이트하시면 됩니다.

[update.zip](https://github.com/user-attachments/files/16490136/update.zip)
 (첨부된 "eth0_static_ip" 파일을 편집기로 열어 사용하실 IP로 IP를 변경 후 사용)

**Comment by taisi5446** [comment]
안녕하십니까 답변감사드립니다.

말씀해주신데로 시도하던중 문제가 생겨 연락드립니다.

보내주신 파일이 윈도우 환경에서 가능하여 윈도우 환경에서 실행하였습니다.

이후 리눅스 환경에서 제품을 연결해 보고자 랜선으로 연결후 ifconfig를 시도하였지만

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::c016:37e5:906f:7376  prefixlen 64  scopeid 0x20<link>
        ether ba:4b:82:fb:ff:f0  txqueuelen 1000  (Ethernet)
        RX packets 24  bytes 6447 (6.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 342  bytes 55746 (55.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

위와같이 IP4번호가 보이지 않습니다.

두개를 소유중인데 둘다 보이지 않습니다.

이와 관련하여 해결방안이 있을까요?

감사합니다.

김태훈드림.


2024년 8월 5일 (월) 오전 11:56, ROBOSCAN AI ***@***.***>님이 작성:

**Comment by nano-roboscan** [comment]
기존에 전달 드린 update.zip에 문제가 있어 다시 전달 드립니다.

전달드리는 파일로도 업데이트가 되지 않으면 

wss@nanosys.kr 로 자세한 내용과 연락처 공유 부탁드립니다.

[update_link.zip](https://github.com/user-attachments/files/16773466/update_link.zip)
